encoding: UTF-8
url: https://gitpage.reccachao.net
title: Recca Chao 的 gitHub page
tagline: 推廣網站開發技術，包含 Laravel 和 Kotlin 後端撰寫
description: 推廣網站開發，包含 Laravel 和 Kotlin 後端撰寫、自動化測試、讀書心得等。Taiwan Kotlin User Group 管理員。
enforce_ssl: gitpage.reccachao.net
locale: zh_TW
theme: jekyll-theme-hacker
google_analytics: UA-78953126-2
logo: /logo.jpg
permalink: pretty
markdown: kramdown
liker_id: recca_chao
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-image-size
